### ISSUE TITLE
INPUT PROBLEM

### ISSUE THREAD

**Issue by tolgabalper** [tolgabalper/MyFirstCalculator#1]
### INPUT LETTER VALUE PROBLEM

- you will get something like this **when you enter another value** then a rational number **( I DID NOT TEST ON IRRATIONALS)**
- Traceback (most recent call last):
  File "/████████/calc.py", line 9, in <module>
    x = float(input(xinput))
ValueError: could not convert string to float: 'a'
- or 
- Traceback (most recent call last):
  File "/████████/calc.py", line 11, in <module>
    x = float(input(xinput))
ValueError: could not convert string to float: 'a'

<sup> █ used for censoring file name and road </sup>

**Comment by tolgabalper** [comment]
UNTIL SOMEONE DECIDED TO ADD FUNCTION TO SOLVE ALGEBRA PROBLEMS IT WILL BE THE ONE OF THE LAST THINGS THAT I WILL ADD
